---
development:
  cloud_name: dsqbi2aqd
  api_key: '875836294774873'
  api_secret: 2ODjxbzdrSstbEOAphaC0hrZI1g
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dsqbi2aqd
  api_key: '875836294774873'
  api_secret: 2ODjxbzdrSstbEOAphaC0hrZI1g
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dsqbi2aqd
  api_key: '875836294774873'
  api_secret: 2ODjxbzdrSstbEOAphaC0hrZI1g
  enhance_image_tag: true
  static_image_support: false
